// Central Material-Symbols -> Font Awesome icon name mapper.
// Usage: <i className={`${mi("close")} text-[18px]`} />
const ICON_MAP = {
    account_tree: "fa-solid fa-sitemap",
    add: "fa-solid fa-plus",
    add_circle: "fa-solid fa-circle-plus",
    arrow_back: "fa-solid fa-arrow-left",
    arrow_forward: "fa-solid fa-arrow-right",
    attach_file: "fa-solid fa-paperclip",
    bolt: "fa-solid fa-bolt",
    bug_report: "fa-solid fa-bug",
    chat: "fa-solid fa-comment",
    chat_bubble_outline: "fa-regular fa-comment",
    check_circle: "fa-solid fa-circle-check",
    chevron_right: "fa-solid fa-chevron-right",
    close: "fa-solid fa-xmark",
    cloud: "fa-solid fa-cloud",
    cloud_done: "fa-solid fa-cloud",
    cloud_off: "fa-solid fa-cloud-arrow-up",
    cloud_sync: "fa-solid fa-rotate",
    cloud_upload: "fa-solid fa-cloud-arrow-up",
    code: "fa-solid fa-code",
    create_new_folder: "fa-solid fa-folder-plus",
    delete: "fa-solid fa-trash",
    delete_outline: "fa-regular fa-trash-can",
    description: "fa-solid fa-file-lines",
    download: "fa-solid fa-download",
    edit: "fa-solid fa-pen",
    error: "fa-solid fa-triangle-exclamation",
    folder: "fa-solid fa-folder",
    folder_managed: "fa-solid fa-folder-tree",
    folder_off: "fa-solid fa-folder-minus",
    folder_open: "fa-solid fa-folder-open",
    format_bold: "fa-solid fa-bold",
    format_italic: "fa-solid fa-italic",
    forum: "fa-solid fa-comments",
    grid_view: "fa-solid fa-table-cells",
    group: "fa-solid fa-users",
    history: "fa-solid fa-clock-rotate-left",
    home: "fa-solid fa-house",
    info: "fa-solid fa-circle-info",
    link: "fa-solid fa-link",
    list: "fa-solid fa-list",
    logout: "fa-solid fa-right-from-bracket",
    mood: "fa-regular fa-face-smile",
    notifications: "fa-solid fa-bell",
    notifications_active: "fa-solid fa-bell",
    person: "fa-solid fa-user",
    person_add: "fa-solid fa-user-plus",
    progress_activity: "fa-solid fa-spinner fa-spin",
    push_pin: "fa-solid fa-thumbtack",
    refresh: "fa-solid fa-arrows-rotate",
    rocket_launch: "fa-solid fa-rocket",
    schedule: "fa-regular fa-clock",
    search: "fa-solid fa-magnifying-glass",
    send: "fa-solid fa-paper-plane",
    settings: "fa-solid fa-gear",
    smart_toy: "fa-solid fa-robot",
    sync: "fa-solid fa-rotate",
    terminal: "fa-solid fa-terminal",
    upload_file: "fa-solid fa-file-arrow-up",
    visibility: "fa-solid fa-eye",
    waving_hand: "fa-regular fa-hand",
    key: "fa-solid fa-key",
    auto_awesome: "fa-solid fa-wand-magic-sparkles",
    dashboard: "fa-solid fa-gauge",
    memory: "fa-solid fa-microchip",
    hub: "fa-solid fa-diagram-project",
    fingerprint: "fa-solid fa-fingerprint",
    science: "fa-solid fa-flask",
    architecture: "fa-solid fa-drafting-compass",
    dataset: "fa-solid fa-database",
    api: "fa-solid fa-plug",
    layers: "fa-solid fa-layer-group",
    database: "fa-solid fa-database",
    play_circle: "fa-solid fa-circle-play",
    keep: "fa-solid fa-thumbtack",
    open_in_new: "fa-solid fa-arrow-up-right-from-square",
    bookmark: "fa-solid fa-bookmark",
    // file-type icons (used by lib/format.js fileVisual())
    image: "fa-solid fa-image",
    movie: "fa-solid fa-film",
    picture_as_pdf: "fa-solid fa-file-pdf",
    present_to_all: "fa-solid fa-file-powerpoint",
    folder_zip: "fa-solid fa-file-zipper",
    draft: "fa-solid fa-file",
    // notification-type icons (used by lib/notifications.js notificationIcon())
    manage_accounts: "fa-solid fa-user-gear",
    person_remove: "fa-solid fa-user-xmark",
};

export function mi(name) {
    if (!name) return "fa-solid fa-circle-question";
    const key = String(name).trim();
    return ICON_MAP[key] || "fa-solid fa-circle-question";
}