/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
darkMode: "class",
          theme: {
            extend: {
              "colors": {
                      "inverse-on-surface": "#2e3037",
                      "on-surface-variant": "#bbc9cd",
                      "tertiary-container": "#bec0ca",
                      "primary-fixed-dim": "#2fd9f4",
                      "tertiary": "#dadce6",
                      "on-tertiary-fixed-variant": "#44474f",
                      "outline": "#859397",
                      "on-primary": "#00363e",
                      "primary": "#8aebff",
                      "surface-tint": "#2fd9f4",
                      "on-tertiary-fixed": "#191c22",
                      "error": "#ffb4ab",
                      "surface-dim": "#111319",
                      "surface-container-low": "#191b22",
                      "surface-variant": "#33343b",
                      "on-tertiary": "#2d3038",
                      "background": "#111319",
                      "primary-fixed": "#a2eeff",
                      "error-container": "#93000a",
                      "inverse-primary": "#006877",
                      "outline-variant": "#3c494c",
                      "surface": "#111319",
                      "on-secondary-container": "#d6a9ff",
                      "surface-container-lowest": "#0c0e14",
                      "on-secondary": "#490080",
                      "on-primary-fixed-variant": "#004e5a",
                      "on-error-container": "#ffdad6",
                      "on-secondary-fixed": "#2c0051",
                      "secondary-fixed": "#f0dbff",
                      "secondary": "#ddb7ff",
                      "surface-container-high": "#282a30",
                      "secondary-container": "#6f00be",
                      "surface-container": "#1e1f26",
                      "on-surface": "#e2e2eb",
                      "inverse-surface": "#e2e2eb",
                      "on-primary-container": "#005763",
                      "on-error": "#690005",
                      "secondary-fixed-dim": "#ddb7ff",
                      "primary-container": "#22d3ee",
                      "surface-bright": "#373940",
                      "tertiary-fixed": "#e0e2ec",
                      "tertiary-fixed-dim": "#c4c6d0",
                      "on-secondary-fixed-variant": "#6900b3",
                      "surface-container-highest": "#33343b",
                      "on-tertiary-container": "#4c4e56",
                      "on-primary-fixed": "#001f25",
                      "on-background": "#e2e2eb"
              },
              "borderRadius": {
                      "DEFAULT": "0.25rem",
                      "lg": "0.5rem",
                      "xl": "0.75rem",
                      "full": "9999px"
              },
              "spacing": {
                      "margin-mobile": "16px",
                      "gutter": "24px",
                      "margin-desktop": "40px",
                      "sidebar-width": "260px",
                      "unit": "4px",
                      "container-max": "1440px"
              },
              "fontFamily": {
                      "headline-lg": ["Geist"],
                      "body-lg": ["Geist"],
                      "code-sm": ["JetBrains Mono"],
                      "label-caps": ["Geist"],
                      "headline-md": ["Geist"],
                      "body-sm": ["Geist"],
                      "headline-lg-mobile": ["Geist"]
              },
              "fontSize": {
                      "headline-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600"}],
                      "body-lg": ["16px", {"lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400"}],
                      "code-sm": ["13px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400"}],
                      "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
                      "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "500"}],
                      "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400"}],
                      "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}]
              }
            },
          },
};
